<?xml version="1.0"?>
<robot name="wheelchair" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- DEFINING GENERIC PROPERTIES THAT ARE USED IN THE XACRO FILE -->

  <!-- along x axis -->
  <xacro:property name="base_dia" value="0.5"/>
  <!-- along y axis -->
  <xacro:property name="base_dia" value="0.5"/>
  <!-- along z axis -->
  <xacro:property name="base_height" value="0.099"/>
  <xacro:property name="base_mass" value="50"/>
  <xacro:property name="wheel_dia" value="0.1"/>
  <xacro:property name="wheel_height" value="0.05"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  <xacro:property name="box_side" value="0.1"/>

  <!-- COLOURS FOR MATERIAL -->
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="black">
    <color rgba ="0 0 0 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

  <!-- MACROS FOR INERTIAL PROPERTIES -->
  <xacro:macro name="base_inertial">
    <inertial>
      <mass value="${base_mass}" />
      <inertia ixx="${(1/12)*base_mass*((base_dia*base_dia)+(base_height*base_height))}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12)*base_mass*((base_height*base_height)+(base_dia*base_dia))}"
        iyz="0.0"
        izz="${(1/12)*base_mass*((base_dia*base_dia)+(base_dia*base_dia))}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="wheel_inertial">
    <inertial>
      <mass value="${wheel_mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="sensor_inertial">
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </xacro:macro>

  <!-- MACRO FOR GENERIC WHEEL. SUPPLY PARAMS TO PLACE THEM, JOINT INCLUDEDE IN MACRO -->
  <xacro:macro name="wheel" params="left_right rely">
    <link name="${left_right}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_dia/2}" length="${wheel_height}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_dia/2}" length="${wheel_height}"/>
        </geometry>
      </collision>
      <xacro:wheel_inertial/>
    </link>

    <joint name="${left_right}_wheel_to_base_link" type="continuous">
      <origin xyz="0 ${rely*((base_dia/2+wheel_height/2))} ${wheel_dia/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${left_right}_wheel"/>
    </joint>
  </xacro:macro>

  <!-- DUMMY ROOT LINK SO THAT BASE LINK CAN BE GIVEN SOME MASS -->
  <link name="root_link"/>

  <!-- BASE LINK. MAIN BOX TO WHICH WHEEL AND EVERYTHING ELSE IS TO BE ATTACHED -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${wheel_dia/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_dia/2}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision name="base_link_collision">
      <origin xyz="0 0 ${wheel_dia/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_dia/2}"/>
      </geometry>
    </collision>
    <xacro:base_inertial/>
  </link>

  <!-- CONNECT BASE LINK TO ROOT LINK -->
  <joint name="base_to_root_joint" type="fixed">
    <parent link="root_link"/>
    <child link="base_link"/>
  </joint>

  <!-- CREATING AN INSTANCE OF EACH WHEEL -->
  <xacro:wheel left_right="left" rely="1"/>
  <xacro:wheel left_right="right" rely="-1"/>

  <!-- LASER LINK -->
  <link name="laser_link">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${box_side} ${box_side} ${box_side}"/>
    </geometry>
    </collision>
    <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
      <box size="${box_side} ${box_side} ${box_side}"/>
      </geometry>
    </visual>
    <xacro:sensor_inertial/>
  </link>

  <joint name="laser_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="0 0 ${base_height + box_side/2}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="laser_link"/>
  </joint>
  
  <!--_______________________ STEREO CAMERA _______________________-->
  <link name="sensor_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${box_side} ${box_side} ${box_side}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${box_side} ${box_side} ${box_side}"/>
      </geometry>
    </visual>

    <xacro:sensor_inertial/>
  </link>

  <!--_______________________ Stereocam Joint _______________________-->
  <joint name="sensor_joint" type="fixed">
    <origin xyz="0 0 ${wheel_dia+1}" rpy="0 0 0"/>
    <axis xyz="1 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="sensor_link"/>
  </joint>

  <!-- SKID STEER PLUGIN -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <updateRate>100.0</updateRate>
      <robotNamespace>/</robotNamespace>
      <leftJoint>left_wheel_to_base_link</leftJoint>
      <rightJoint>right_wheel_to_base_link</rightJoint>
      <wheelSeparation>0.5</wheelSeparation>
      <wheelDiameter>0.1</wheelDiameter>
      <wheelAcceleration>0.5</wheelAcceleration>
      <wheelTorque>50</wheelTorque>
      <robotBaseFrame>base_link</robotBaseFrame>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <broadcastTF>false</broadcastTF>
      <odometryFrame>odom</odometryFrame>
      <odometrySource>world</odometrySource>
      <publishOdomTF>true</publishOdomTF>
      <robotBaseFrame>base_link</robotBaseFrame>
      <publishWheelTF>false</publishWheelTF>
      <publishTf>true</publishTf>
      <publishWheelJointState>true</publishWheelJointState>
      <legacyMode>false</legacyMode>
      <rosDebugLevel>na</rosDebugLevel>
    </plugin>
  </gazebo>

  <!-- JOINT STATE PUBLISHER -->
  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <jointName>left_wheel_to_base_link, right_wheel_to_base_link</jointName>
    </plugin>
  </gazebo>

    <!-- LASER PLUGIN -->
  <gazebo reference="laser_link">
    <sensor type="ray" name="laser">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>40</update_rate>
      <ray>
      <scan>
      <horizontal>
        <samples>720</samples>
        <resolution>1</resolution>
        <min_angle>-3.14159</min_angle>
        <max_angle>3.14159</max_angle>
      </horizontal>
      </scan>
      <range>
      <min>0.10</min>
      <max>30.0</max>
      <resolution>0.01</resolution>
      </range>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>laser_link</frameName>
      </plugin>
    </sensor>
  </gazebo>
  
  <gazebo reference="sensor_link">
    <sensor type="multicamera" name="stereo_camera">
      <update_rate>30.0</update_rate>
      <camera name="left">
      <pose>${box_side} ${box_side/2} 0 0 0 0</pose>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <camera name="right">
        <pose>${box_side} -${box_side/2} 0 0 0 0</pose>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="stereo_camera_controller" filename="libgazebo_ros_multicamera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>30.0</updateRate>
        <cameraName>stereo</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>sensor_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>

</robot>
